// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelTokenPricing = { currency: string, inputCacheHitUsdMicrosPerMillionTokens: bigint | null, inputCacheMissUsdMicrosPerMillionTokens: bigint | null, outputUsdMicrosPerMillionTokens: bigint | null, reasoningOutputUsdMicrosPerMillionTokens: bigint | null, };
